### ISSUE TITLE
Pass `lang` parameter only for built-in content

### ISSUE THREAD

**Issue by IngmarStein** [savdagod/TidbytAssistant#12]
The. description says "Language to display built-in content", but the `lang` parameter is actually also set for custom content.
I think we shouldn't set the `lang` parameter for custom content which may support more than the two languages provided by the built-in apps.

I'm running a custom app which happens to use the `lang` parameter and I've been passing this as part of the arguments list and was wondering why it wasn't passed to the add-on: it's because I didn't check the `Language` checkbox which then causes the `lang` parameter to be set to an empty value.

**Comment by savdagod** [comment]
Ah yeah that makes sense, it’s an easy fix. 


I keep wondering if now it would be better to split the services between built-in and custom rather than Push and Publish. To me it now makes more sense to group the services by the parameters they use (ie only built-in params will be in the built in service, same with custom). Problem with that is it’s going to break everyone’s automations.

**Comment by savdagod** [comment]
Fixed in 1.0.12

**Comment by savdagod** [comment]
Yeah, given its `pixlet push <app>` I will remove the publish service and consolidate everything into the push service. That way, users will only have to edit their automations that use publish to push, which should be as easy as just changing the name as the variables will be the same.

**Comment by IngmarStein** [comment]
"Push" makes more sense than "publish" in the user-facing component. Should we require another mandatory add-on update and rename the `/tidbyt-publish` endpoint to `/push`? This would only be to align terminology with the integration.
